import { Button } from "@/components/ui/button";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>🧨 TNT Stack Starter 🧨</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex items-center flex-col gap-4 justify-center h-screen">
          <h2 className="font-bold text-4xl">🧨 TNT Stack Starter 🧨</h2>
          <p className="text-2xl">Typescript + Next.js + TailwindCSS</p>
          <Button className="my-4">👋 Say Hello to MC.Naveen</Button>
        </div>
      </main>
    </>
  );
}
